using FlexQuery.NET.Execution;
using FlexQuery.NET.Models;
using FlexQuery.NET.Models.Aggregates;
using FlexQuery.NET.Options;
using FlexQuery.NET.Validation;
using FlexQuery.NET.Validation.Rules;

namespace FlexQuery.NET.Tests.Validation;

public class AggregateValidationRuleTests
{
    
    private static QueryContext Context(Type? targetType = null, QueryGovernanceOptions? execOptions = null) =>
        new() { TargetType = targetType ?? typeof(Order), ExecutionOptions = execOptions };

    private static ValidationResult Validate(QueryOptions options)
    {
        var rule = new AggregateValidationRule();
        var result = ValidationResult.Success();
        rule.Validate(options, Context(), result);
        return result;
    }

    [Fact]
    public void EmptyAggregates_Passes()
    {
        var options = new QueryOptions { Aggregates = [] };
        var result = Validate(options);

        result.IsValid.Should().BeTrue();
    }

    [Fact]
    public void NoAlias_AutoGenerated_Passes()
    {
        var options = new QueryOptions
        {
            Aggregates = [new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "TotalSum" }]
        };
        var result = Validate(options);

        result.IsValid.Should().BeTrue();
    }

    [Fact]
    public void ExplicitAlias_ValidIdentifier_Passes()
    {
        var options = new QueryOptions
        {
            Aggregates = [new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "TotalSales" }]
        };
        var result = Validate(options);

        result.IsValid.Should().BeTrue();
    }

    [Fact]
    public void ExplicitAlias_StartsWithDigit_FailsWithInvalidAlias()
    {
        var options = new QueryOptions
        {
            Aggregates = [new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "123Total" }]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.InvalidAlias);
    }

    [Fact]
    public void ExplicitAlias_ContainsHyphen_FailsWithInvalidAlias()
    {
        var options = new QueryOptions
        {
            Aggregates = [new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "total-sales" }]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.InvalidAlias);
    }

    [Fact]
    public void ExplicitAlias_ContainsSpace_FailsWithInvalidAlias()
    {
        var options = new QueryOptions
        {
            Aggregates = [new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "total sales" }]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.InvalidAlias);
    }

    [Fact]
    public void ExplicitAlias_ContainsDot_FailsWithInvalidAlias()
    {
        var options = new QueryOptions
        {
            Aggregates = [new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "total.sales" }]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.InvalidAlias);
    }

    [Fact]
    public void ExplicitAlias_ContainsSpecialChar_FailsWithInvalidAlias()
    {
        var options = new QueryOptions
        {
            Aggregates = [new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "total!" }]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.InvalidAlias);
    }

    [Theory]
    [InlineData("SELECT")]
    [InlineData("WHERE")]
    [InlineData("GROUP")]
    [InlineData("BY")]
    [InlineData("HAVING")]
    [InlineData("AGGREGATE")]
    [InlineData("AND")]
    [InlineData("OR")]
    [InlineData("NOT")]
    [InlineData("IN")]
    [InlineData("LIKE")]
    [InlineData("BETWEEN")]
    [InlineData("IS")]
    [InlineData("CONTAINS")]
    [InlineData("STARTSWITH")]
    [InlineData("ENDSWITH")]
    [InlineData("ANY")]
    [InlineData("ALL")]
    [InlineData("AS")]
    [InlineData("ASC")]
    [InlineData("DESC")]
    [InlineData("NULL")]
    [InlineData("TRUE")]
    [InlineData("FALSE")]
    public void ReservedKeyword_Alias_FailsWithReservedAlias(string reservedAlias)
    {
        var options = new QueryOptions
        {
            Aggregates = [new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = reservedAlias }]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.ReservedAlias);
    }

    [Fact]
    public void DuplicateAlias_Explicit_FailsWithDuplicateAlias()
    {
        var options = new QueryOptions
        {
            Aggregates =
            [
                new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "Total" },
                new AggregateModel { Function = AggregateFunction.Avg, Field = "Price", Alias = "Total" }
            ]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.DuplicateAlias);
    }

    [Fact]
    public void DuplicateAlias_CaseInsensitive_FailsWithDuplicateAlias()
    {
        var options = new QueryOptions
        {
            Aggregates =
            [
                new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "Total" },
                new AggregateModel { Function = AggregateFunction.Avg, Field = "Price", Alias = "total" }
            ]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.DuplicateAlias);
    }

    [Fact]
    public void DuplicateAlias_AutoGeneratedVsExplicit_FailsWithDuplicateAlias()
    {
        var options = new QueryOptions
        {
            Aggregates =
            [
                new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "TotalSum" },
                new AggregateModel { Function = AggregateFunction.Count, Field = "Id", Alias = "TotalSum" }
            ]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.DuplicateAlias);
    }

    [Fact]
    public void InvalidAggregateTarget_SumWildcard_FailsWithInvalidAggregateTarget()
    {
        var options = new QueryOptions
        {
            Aggregates = [new AggregateModel { Function = AggregateFunction.Sum, Field = null, Alias = "SumAll" }]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.InvalidAggregateTarget);
    }

    [Fact]
    public void InvalidAggregateTarget_AvgWildcard_FailsWithInvalidAggregateTarget()
    {
        var options = new QueryOptions
        {
            Aggregates = [new AggregateModel { Function = AggregateFunction.Avg, Field = null, Alias = "AvgAll" }]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.InvalidAggregateTarget);
    }

    [Fact]
    public void InvalidAggregateTarget_MinWildcard_FailsWithInvalidAggregateTarget()
    {
        var options = new QueryOptions
        {
            Aggregates = [new AggregateModel { Function = AggregateFunction.Min, Field = null, Alias = "MinAll" }]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.InvalidAggregateTarget);
    }

    [Fact]
    public void InvalidAggregateTarget_MaxWildcard_FailsWithInvalidAggregateTarget()
    {
        var options = new QueryOptions
        {
            Aggregates = [new AggregateModel { Function = AggregateFunction.Max, Field = null, Alias = "MaxAll" }]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.InvalidAggregateTarget);
    }

    [Fact]
    public void ValidAggregateTarget_CountWildcard_Rejected()
    {
        var options = new QueryOptions
        {
            Aggregates = [new AggregateModel { Function = AggregateFunction.Count, Field = "*", Alias = "TotalCount" }]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.InvalidAggregateTarget);
    }

    [Fact]
    public void ValidAggregateTarget_SumProperty_Passes()
    {
        var options = new QueryOptions
        {
            Aggregates = [new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "TotalSum" }]
        };
        var result = Validate(options);

        result.IsValid.Should().BeTrue();
    }

    [Fact]
    public void MultipleErrors_Accumulated()
    {
        var options = new QueryOptions
        {
            Aggregates =
            [
                new AggregateModel { Function = AggregateFunction.Sum, Field = null, Alias = "SELECT" },
                new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "SELECT" }
            ]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().HaveCount(4);
        result.Errors.Should().Contain(e => e.Code == ValidationErrorCodes.ReservedAlias);
        result.Errors.Should().Contain(e => e.Code == ValidationErrorCodes.DuplicateAlias);
        result.Errors.Should().Contain(e => e.Code == ValidationErrorCodes.InvalidAggregateTarget);
    }

    [Fact]
    public void DuplicateAggregateDefinition_SameFunctionAndField_Fails()
    {
        var options = new QueryOptions
        {
            Aggregates =
            [
                new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "TotalSum" },
                new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "TotalSum2" }
            ]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.DuplicateAggregateDefinition);
    }

    [Fact]
    public void DuplicateAggregateDefinition_DifferentAliases_Fails()
    {
        var options = new QueryOptions
        {
            Aggregates =
            [
                new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "Sales" },
                new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "Revenue" }
            ]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.DuplicateAggregateDefinition);
    }

    [Fact]
    public void DuplicateAggregateDefinition_DifferentFunction_Passes()
    {
        var options = new QueryOptions
        {
            Aggregates =
            [
                new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "TotalSum" },
                new AggregateModel { Function = AggregateFunction.Avg, Field = "Total", Alias = "AvgTotal" }
            ]
        };
        var result = Validate(options);

        result.IsValid.Should().BeTrue();
    }

    [Fact]
    public void DuplicateAggregateDefinition_DifferentField_Passes()
    {
        var options = new QueryOptions
        {
            Aggregates =
            [
                new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "TotalSum" },
                new AggregateModel { Function = AggregateFunction.Sum, Field = "Price", Alias = "PriceSum" }
            ]
        };
        var result = Validate(options);

        result.IsValid.Should().BeTrue();
    }

    [Fact]
    public void DuplicateAggregateDefinition_CaseInsensitiveField_Fails()
    {
        var options = new QueryOptions
        {
            Aggregates =
            [
                new AggregateModel { Function = AggregateFunction.Sum, Field = "Total", Alias = "TotalSum" },
                new AggregateModel { Function = AggregateFunction.Sum, Field = "total", Alias = "TotalSum2" }
            ]
        };
        var result = Validate(options);

        result.IsValid.Should().BeFalse();
        result.Errors.Should().ContainSingle(e => e.Code == ValidationErrorCodes.DuplicateAggregateDefinition);
    }
}
