using System.Linq.Expressions;
using FlexQuery.NET.Builders;
using FlexQuery.NET.Debug;
using FlexQuery.NET.Models;

namespace FlexQuery.NET;

/// <summary>
/// Extensions for debugging FlexQuery operations.
/// </summary>
public static class FlexQueryDebugExtensions
{
    /// <summary>
    /// Analyzes the query application process and returns a detailed debug result.
    /// Does not execute the query.
    /// </summary>
    /// <typeparam name="T">The entity type.</typeparam>
    /// <param name="query">The base queryable.</param>
    /// <param name="options">The query options to apply.</param>
    /// <returns>A <see cref="DebugResult"/> containing AST and Expression details.</returns>
    public static DebugResult ToFlexQueryDebug<T>(this IQueryable<T> query, QueryOptions options)
    {
        var result = new DebugResult
        {
            Ast = options.Ast
        };

        // We use a dummy provider to capture the expression tree generated by QueryBuilder
        var queryParam = Expression.Parameter(typeof(IQueryable<T>), "query");
        var debugProvider = new DebugQueryProvider();
        var debugQuery = new DebugQueryable<T>(queryParam, debugProvider);

        // Apply the options through the standard QueryBuilder
        var applied = QueryBuilder.Apply(debugQuery, options);
        
        // If projection is present, apply it too
        IQueryable appliedFinal = applied;
        if (options.Select?.Count > 0 || options.Aggregates.Count > 0 || (options.GroupBy?.Count ?? 0) > 0)
        {
            appliedFinal = QueryBuilder.ApplySelect(applied, options);
        }

        result.LinqLambda = ExpressionPrinter.Print(appliedFinal.Expression);
        result.ExpressionTree = ExpressionTreeVisualizer.Visualize(appliedFinal.Expression);

        return result;
    }

    private sealed class DebugQueryProvider : IQueryProvider
    {
        public IQueryable CreateQuery(Expression expression)
        {
            var elementType = GetElementType(expression.Type);
            var queryType = typeof(DebugQueryable<>).MakeGenericType(elementType);
            return (IQueryable)Activator.CreateInstance(queryType, expression, this)!;
        }

        public IQueryable<TElement> CreateQuery<TElement>(Expression expression)
            => new DebugQueryable<TElement>(expression, this);

        public object? Execute(Expression expression) => null;
        public TResult Execute<TResult>(Expression expression) => default!;

        private static Type GetElementType(Type type)
        {
            var iface = type.GetInterfaces()
                .FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEnumerable<>));
            return iface?.GetGenericArguments()[0] ?? type;
        }
    }

    private sealed class DebugQueryable<T> : IQueryable<T>
    {
        public DebugQueryable(Expression expression, IQueryProvider provider)
        {
            Expression = expression;
            Provider = provider;
        }

        public Type ElementType => typeof(T);
        public Expression Expression { get; }
        public IQueryProvider Provider { get; }

        public IEnumerator<T> GetEnumerator() => Enumerable.Empty<T>().GetEnumerator();
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
    }
}
